### ISSUE TITLE
Именование модификаторов

### ISSUE THREAD

**Issue by chmnkh** [alextsk/blog-markup#17]
Модификаторы типа ключ-значение стоит называть соответствующим образом: arrow-button--direction--left, button--size--big и так далее, а не просто button--big, например.

**Comment by chmnkh** [comment]
К этому и к #16 посмотри комменты в пулл реквестах и создай новые, я автоматически их вмержил случайно.

**Comment by chmnkh** [comment]
У button есть странный параметр: theme, который во-первых не булевый, а классы которые он задает, названы так, как будто он булевый. Во-вторых: то, что "error" и "small-padding" - это темы, это супер-странно. В-третьих: small-padding - вообще плохое название, не надо модификаторы называть, исходя из css-свойств, абстрагируйся от этого и называй по общему смыслу, не надо думать, какие ты там стили для этого напишешь. В-четвертых: странно было такие разные свойства элемента вообще одним параметром связывать, на мой взгляд.

**Comment by chmnkh** [comment]
```
.input__message.input__message--error=errMessage
.input__message.input__message--success=sucMessage
```
тут то же неверно, + я не увидел стилей для этих модификаторов вообще)

**Comment by alextsk** [comment]
что именно не так c error и fill?

**Comment by chmnkh** [comment]
1) они взаимоисключающие, а названы у тебя так, как будто они булевые и самостоятельные
2) модификатор не может быть тупо существительным
еще раз: почитай стандарты, там достаточно хорошо описано, как нужно называть модифкаторы

**Comment by alextsk** [comment]
> взаимоисключающие
именно fill  и error независимы, они могут быть на одной кнопке

> почитай стандарты

 я читал, но с именно с кнопкой непонятно - т.е. filled  и  erroneous  уже норм?

**Comment by chmnkh** [comment]
filled - нормально, erroneous - это жесть уже) в тех же стандартах прямо пример есть именования блока с error.
Нормально или нет ты назвал модификатор, проверить легко: имя модификатора должно отвечать на вопрос "какой" по отношению к модифицируемому элементу. Если же у тебя модификатор назван просто существительным или глаголом - это уже не то. 
Про взаимоисключаемость я имел в виду error и success. Имя как бы намекает, что они у тебя взаимоисключающие, т.е. булевыми модификаторами они быть не могут как минимум уже по этому. Если это не так и они вообще о разном, то тут опять же с именами что-то не то, потому что уже неочевидности вылазить начинают.

**Comment by alextsk** [comment]
row_with-error - если ты об этом, там row  содержит error, у меня же баттон саму ошибку не содержит, это просто цветовое кодирование

**Comment by chmnkh** [comment]
Если это просто цвет, то причем здесь error тогда вообще?)

**Comment by alextsk** [comment]
--for-accept и --for--decline лучше?

**Comment by chmnkh** [comment]
а почему не --color--{цвет}
модификатор же цвет задает?

**Comment by alextsk** [comment]
а как же семантика? smallPadding  паддинг задает

**Comment by chmnkh** [comment]
А какой смысл в себе может нести модификатор "ошибки" на кнопке, и где это в макете? Вот если бы у тебя какой-нибудь инпут был, например, и после неудачной валидации ты бы на него не color_red модификатор вешал, a invalid, вот это было бы верно, потому что то, что инпут стал красный - несет в себе смысл - инпут инвалидный. А вот то, что у тебя кнопка красная в данном случае несет смысл лишь того, что она красная, и ничего больше. Хотя если бы тот же инпут был именно красным всегда, потому что тема например такая, тогда там уже color_red.
А называя элемент smallPadding или как-нибудь еще типа bigMargin, positionAbsolute и т.д, ты лишаешь себя абстракции и завязываешь свои классы на конкретные css-стили, тогда как давая название любой бэм-сущности, ты должен думать только в рамках предметной области, а не в рамках того, как конкретно ты будешь им внешний вид задавать. То, что у тебя паддингами задается сейчас, завтра может задаваться уже флексом, или позиционированием, или еще чем-то, не надо детали реализации лишний раз раскрывать там, где это не нужно.
