### ISSUE TITLE
Perfect Pixel

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [alextsk/blog-markup#2]
Выложи плиз скрин экрана в инверсии и настройки Perfect Pixel, которыми ты пользовался для верстки ui-kit.

**Comment by alextsk** [comment]
![ui_kit_inv](https://user-images.githubusercontent.com/16453186/44323537-90f9f380-a47c-11e8-8769-29f006c30481.png)

**Comment by ValentinAlexandrovich** [comment]
Скинь плиз ссылку на эту страницу

**Comment by alextsk** [comment]
https://alextsk.github.io/blog-markup/ui/
в ридми ссылки на uikit  и на  пример использования
https://github.com/alextsk/blog-markup/tree/standarts

**Comment by ValentinAlexandrovich** [comment]
На момент написания ишью на gh-pages отображалось по другому, видимо ты обновил макет. Тут имеются существенные отхождения от макета:
Общее: Шрифт для именования секций, подбери плиз похожий, если не найдешь тот что указан в макете, и без засечек. 
1) Buttons - Восклицательный знак? Сделай плиз риппл эффект более медленным, и уменьши начальное значение окружности, чтобы можно было определить точку возникновения окружности. Измени курсор при наведении на кнопки.
2) arrow - сделай плиз направления кнопок как в макете
3) PieChart - подправь плиз соотношения
4) Slider - не скрывай плиз первом слайдере значение ползунка, это не удобно с точки зрению ui, числовое значение сделай без сотых, как в макете, доведи до внешнего соответствия с макета )шрифт и размеры для цифр и таблички ползунка. Для дискретного слайдера пожалуйста сделай разбиение в соответствии с макетом, и подправь шрифт и размер снизу Числовое табло в дискретном делать не обязательно, все подписи имеются снизу убери его.
5) Stages - размеры, шрифт и позиционирование цифр.
6) Form - отсутствует placeholder для текстовых полей. Поведение форм элементов, сделай плиз динамику на этих элементах для error и thanks!  регулярное выражение для сопоставления текста с шаблоном, на твое усмотрение. Для элементов error и thanks! подправь плиз размеры, шрифт и позиционирование текста.
7) Toggles - размеры, шрифт и позиционирование текста.
8) Tick Boxes - отсутствует темная галочка на сером фоне.
9) Search \ DropDown - отсутствует placeholder для текстовых полей. Исходя из макета видно, что оранжевое поле выводится при отсутствии искомого текста. Реализуй плиз это ui. Поиск по странице можешь не пилить, будет достаточно если при нажатии на поиск будет выводится текст об отсутствии найденного, а при клике на поле исходно поле, возвращаться в исходное состояние без placeholder, с возможностью ввода теста. Исходное состояние при загрузке странички, согласно макету. Для DropDown помимо placeholder реализуй плиз визуальное разделение option, чтобы было понятно какой выбираешь. И убери плиз огромный отступ поз последим.
10) User profile - подправь плиз  цвет текста согласно черный на серый согласно макета.
11) News & Event- подправь шрифт на без засечек.
12) Location - отсутствует маркер на карте.
13) Calendar - шрифт, отступ над mon tue... Поменяй плиз курсор при наведении на today чтобы было понятно что это не просто текст. 
14) Messaging - отсутствует placeholder для текстового поля. Шрифт для первого сообщения.

**Comment by alextsk** [comment]
немного напутал в путях к шрифтам, у меня похоже локально установлен Лато, и я не видел ошибки. сейчас проблемы связанные со шрифтами должны решиться, можешь глянуть еще раз?

**Comment by ValentinAlexandrovich** [comment]
Да, проблема с типом шрифта ушла.

**Comment by alextsk** [comment]
пара вопросов:
arrow - сделай плиз направления кнопок как в макете - можешь подробнее описать проблему?(или скриншот)
Messaging - отсутствует placeholder для текстового поля - это ведь не плейсхолдер, там из текста видно что это начало ответного сообщения?
по остальным все понятно, исправляю.
я правильно понимаю по этому ишью один пулл реквест, по мере сделанного буду туда добавлять коммиты?

**Comment by ValentinAlexandrovich** [comment]
Arrow, сейчас из макета складывается ощущение что у тебя есть только задизейблейные кнопки стрелкой направо и просто arrow со стрелой налево, сделай в макете плиз чтобы было видно что эти типы есть со стрелками повернутыми в разные стороны. 
Messaging  - да, но если продолжить твою мысль там еще там видно, что это messager, а не просто блок с div-ками. Думаю довести placeholder до состояние макета займет меньше времени на исправление. Еще обнаружил баг, что при вводе текста начинает увеличиваться высота messaginga. 
Да, один пулл реквест  на ишью.

**Comment by ValentinAlexandrovich** [comment]
Если через  placeholder не получится, можно просто вставить текст со стилями в textarea.

**Comment by alextsk** [comment]
вроде все поправил, добавься, пожалуйста, в коллабораторы на этот репозиторий, чтобы я мог тебя назначить на пулл реквест
