### ISSUE TITLE
Убрать ворнинги линтера

### ISSUE THREAD

**Issue by chmnkh** [alextsk/blog-markup#32]
Зашел я, например, в js календаря, а он весь красный)

**Comment by chmnkh** [comment]
![image](https://user-images.githubusercontent.com/18498637/45155347-e49e6800-b204-11e8-8640-d8da8cbe1a7a.png)
я же все верно открыл?)

**Comment by alextsk** [comment]
не факт. верно это gulp lint - будет работать по "airbnb-base", а откуда твой редактор правила берет я не знаю.

**Comment by chmnkh** [comment]
Ну код тот? Если да, то тут миллион вещей не по airbnb.

**Comment by alextsk** [comment]
код почти тот(не совсем календарь), но я не могу убрать ворнинги твоего линтера, у меня сейчас 19 ошибок и про карту там одна. 

> 
D:\test\blog-markup\src\components\location\index.js
  22:11  error  'marker' is assigned a value but never used  no-unused-vars

при этом правила он нашел 

> (node:7848) [ESLINT_LEGACY_OBJECT_REST_SPREAD] DeprecationWarning: The 'parserOp                      tions.ecmaFeatures.experimentalObjectRestSpread' option is deprecated. Use 'pars                      erOptions.ecmaVersion' instead. (found in "**airbnb-base**")

что я делаю не так?
