### ISSUE TITLE
Не помещать в span div

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [alextsk/blog-markup#44]
Объясни почему тут так делать не стоит и пройдись по проекту чтобы подправить это, к примеру в стэйжах:
 span.stage__point.stage__point--active 1
        - for (var x = 1; x < total; x++)
            - step--
            if step > 0
                .stage__line.stage__line--active
                span.stage__point.stage__point--active=x+1

**Comment by alextsk** [comment]
в стейджах нет дивов в спане
```
        span.stage__point.stage__point--active 1
        - for (var x = 1; x < total; x++)
            - step--
            if step > 0
                .stage__line.stage__line--active
                span.stage__point.stage__point--active=x+1
            else
                .stage__line
                span.stage__point=x+1
```
в этом примере for в том же столбце что и первый спан, его результат - сиблинги а не дети.
 нигде блочные в инлайновых не лежат. 
вообще ни тех ни тех тут нет, они flex-children
