### ISSUE TITLE
Избыточность классов

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [alextsk/blog-markup#47]
Можешь объяснить плиз почему ты используешь к примеру wrapper__sliders, и не можешь обойтись внутренним sliders-section? Так ли необходим класс section-header? И как он вписывается в иерархию согласно БЭМ?

**Comment by alextsk** [comment]
потому что согласно БЭМ нельзя на сам sliders-section задать позиционирование марджинами относительно других секций, ну и удобнее взаимные отношения секций задать в одном общем родителе. section-header нужен чтобы легко поменять в одном месте стили заголовков, которые явно должны быть одинаковы для всех секций, про иерархию не понял вопрос, это блок, они все на одном уровне иерархии.

**Comment by ValentinAlexandrovich** [comment]
Согласен что нельзя, ну так ты можешь задать ему размеры, либо паддинги для отступов от вложенных элементов. тем самым подогнав до нужных размеров макет.  section-header не вписывается по БЭМу, удали его из блоков. Вот представь сейчас у тебя так реализовано, но допустим кто то будет поддерживать твой код, и решит добавить стили дополнительные в твой класс section-header не зная о том что он переиспользуется в куче других мест, и верстка полетит. А уструктуры проектов бывают очень запутанные, так что не стоит делать такое смешение.

**Comment by alextsk** [comment]
весь смысл блока в том, что если кто-то решит добавить стили они везде поменяются. как он не вписывается в БЭМ? блоки могут содержать другие блоки, чужие стили в него не лезут. я просто не понимаю альтернативы, stylus mixin? или ты считаешь что копипастить эти стили и менять их потом в 15 местах каждый раз лучше?

**Comment by alextsk** [comment]
он вложен    
```
 h1.sliders-section__header
      +section-header("Sliders")
```
и оформлен миксином. 
может ты другую ветку смотришь? 
он был примиксован раньше https://github.com/alextsk/blog-markup/issues/14

**Comment by ValentinAlexandrovich** [comment]
Я смотрю твой ui-kit и там он примиксован,
![2018-09-11 14-54-35](https://user-images.githubusercontent.com/31854808/45346573-b9849180-b5d3-11e8-9901-c7e651d60a7e.png)
А во врапперах ты их не надуваешь паддингами?) Нет, не лучше, конкретно здесь лучше руководствоваться правилом о необходимой достаточности.

**Comment by ValentinAlexandrovich** [comment]
Лучше, но избыточность так и осталась, не стоит на каждый чих создавать отдельный блок (это ухудшает читаемость проекта, учебные проекты достаточно просты, а на реальных проектах это крайне неудобно, и не пройдет ревью), тем более когда присутствует вполне логичная альтернатива.

**Comment by alextsk** [comment]
ок, я тебя правильно понял, альтернатива это тот же миксин только в стилусе, и полностью разобрать wrapper сложив секции в body ?

**Comment by ValentinAlexandrovich** [comment]
да
