### ISSUE TITLE
Обнови gh-pages

### ISSUE THREAD

**Issue by ValentinAlexandrovich** [alextsk/blog-markup#5]

**Comment by alextsk** [comment]
обновил

**Comment by ValentinAlexandrovich** [comment]
Два замечания: 
1) отсутствует маркер на картах
![2018-08-25 10-57-42](https://user-images.githubusercontent.com/31854808/44614992-6da6be00-a859-11e8-8831-16e20e6497e3.png)
2) странное поведение риппл эффекта на кнопках, причем баг появляется спонтанно и в каждом случае по разному, в основном после нажатий на другие компоненты, чекбоксы, арров, часто после зажатия и перетаскивания маркера на дискретном слайдере, в обще вот гифка, чтобы было понятней.
![bug1](https://user-images.githubusercontent.com/31854808/44615016-d857f980-a859-11e8-9490-beb1add34a7e.gif)

**Comment by alextsk** [comment]
поправил. коммитить в старый пулл реквест или новую ветку для этого ишью создать?

**Comment by ValentinAlexandrovich** [comment]
создай новую
